name: 'Terraform Apply InfraCode [PROD]'

on:
  # 1. Listen SPECIFICALLY for the PROD Plan workflow to finish
  workflow_run:
    workflows: ["Terraform Plan InfraCode [PROD]"]
    types:
      - completed
    branches:
      - main
  # 2. Allow manual triggers for PROD specifically
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply-prod:
    name: 'Apply [PROD]'
    # 3. Only run if the PROD Plan succeeded, OR if triggered manually
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: windows-latest
    
    # 4. Triggers the PROD Email Approval Gate
    environment: prod 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          
      - name: Terraform Init
        run: terraform init
        working-directory: .\environment\LearningGallery\Infra-IaC-Code\prod 

      - name: Run Apply Script
        shell: pwsh
        run: .\environment\LearningGallery\Infra-IaC-Code\prod\Terraform-Scripts\Apply-Terraform.ps1 -Action "apply" -Environment "prod" -Path ".\environment\LearningGallery\Infra-IaC-Code\prod"
        env:
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_windows_admin_password: ${{ secrets.WINDOWS_ADMIN_PASSWORD }}