name: 'Terraform Plan InfraCode'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual run
    inputs:
      environment:
        description: 'Environment to Apply'
        required: true
        default: 'uat'
        type: choice
        options: [uat, prod]
  

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: 'Plan [${{ matrix.environment }}]'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [uat, prod]
        include:
          - environment: uat
            path: ./environment/LearningGallery/Infra-IaC-Code/uat
          - environment: prod
            path: ./environment/LearningGallery/Infra-IaC-Code/prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Plan Script
        shell: pwsh
        run: |
          .\Terraform-Scripts\Apply-Terraform.ps1 `
            -Action "plan" `
            -Environment ${{ matrix.environment }} `
            -Path ${{ matrix.path }}
        env:
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_windows_admin_password: ${{ secrets.WINDOWS_ADMIN_PASSWORD }}

      - name: Debug Output Runner Directory
        shell: pwsh
        run: |
            Write-Output "Current Directory: $PWD"
            Write-Output "Folder Contents:"
            Get-ChildItem -Recurse -Depth 2   
    